services:
  backend:
    build: ./backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: jogo_dos_culpados
      DB_USER: root
      DB_PASSWORD: root
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: 123456
      ADMIN_SECRET: quem-fez-isso-local
      PLAYER_SECRET: quem-fez-isso-player-local

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:8080

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: jogo_dos_culpados
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./backend/database/seeds.sql:/docker-entrypoint-initdb.d/02-seeds.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql_data:
