INSERT INTO categories (slug, name) VALUES
('amizade', 'Amizade'),
('cotidiano', 'Cotidiano'),
('festa', 'Festa'),
('aventura', 'Aventura'),
('caos', 'Caos'),
('geral', 'Geral');

INSERT INTO questions (text, category, level) VALUES
('Quem mais provavelmente chegaria atrasado ate no proprio aniversario?', 'amizade', 'leve'),
('Quem mais provavelmente faria drama por uma coisa minima?', 'amizade', 'leve'),
('Quem mais provavelmente esqueceria onde estacionou o carro?', 'cotidiano', 'leve'),
('Quem mais provavelmente pediria comida e se arrependeria depois?', 'cotidiano', 'leve'),
('Quem mais provavelmente mandaria audio de cinco minutos?', 'amizade', 'leve'),
('Quem mais provavelmente toparia uma viagem sem planejar nada?', 'aventura', 'medio'),
('Quem mais provavelmente criaria uma teoria absurda e defenderia ate o fim?', 'caos', 'caos'),
('Quem mais provavelmente sumiria do grupo e voltaria como se nada tivesse acontecido?', 'amizade', 'medio'),
('Quem mais provavelmente riria na hora errada?', 'caos', 'leve'),
('Quem mais provavelmente gastaria dinheiro com algo inutil e chamaria de investimento?', 'cotidiano', 'medio'),
('Quem mais provavelmente viraria amigo de alguem na fila?', 'amizade', 'leve'),
('Quem mais provavelmente perderia o celular dentro de casa?', 'cotidiano', 'leve'),
('Quem mais provavelmente inventaria uma desculpa criativa para nao sair?', 'amizade', 'medio'),
('Quem mais provavelmente cantaria errado com muita confianca?', 'festa', 'leve'),
('Quem mais provavelmente comeria a ultima fatia sem perguntar?', 'festa', 'medio'),
('Quem mais provavelmente demoraria mais para escolher um filme?', 'cotidiano', 'leve'),
('Quem mais provavelmente salvaria o rolê de ultima hora?', 'festa', 'leve'),
('Quem mais provavelmente transformaria qualquer assunto em debate?', 'caos', 'medio'),
('Quem mais provavelmente compraria passagem no impulso?', 'aventura', 'medio'),
('Quem mais provavelmente dormiria no meio da festa?', 'festa', 'leve'),
('Quem mais provavelmente esqueceria o nome de alguem que acabou de conhecer?', 'cotidiano', 'leve'),
('Quem mais provavelmente faria uma promessa que nao vai cumprir?', 'caos', 'medio'),
('Quem mais provavelmente levaria lanchinho para todo mundo?', 'amizade', 'leve'),
('Quem mais provavelmente responderia mensagem tres dias depois?', 'amizade', 'leve'),
('Quem mais provavelmente ficaria encarregado da playlist?', 'festa', 'leve'),
('Quem mais provavelmente escolheria o pior caminho no GPS?', 'aventura', 'medio'),
('Quem mais provavelmente pediria desconto com coragem total?', 'cotidiano', 'medio'),
('Quem mais provavelmente ficaria famoso por um motivo aleatorio?', 'caos', 'caos'),
('Quem mais provavelmente faria amizade com o garcom?', 'festa', 'leve'),
('Quem mais provavelmente mudaria de opiniao em cinco minutos?', 'caos', 'medio');
